### ISSUE TITLE
where is the Detector constructor and  detect_resized function in yolo_v2_class.h

### ISSUE THREAD

**Issue by xiaozhuka** [phongnhhn92/lightDenseYOLO#1]
When build the project, errors occurred:
mainwindow.o：在函数‘MainWindow::MainWindow(QWidget*)’中：
/home/lisaliu/code/build-TestDarkNet-Desktop_Qt_5_10_1_GCC_64bit-Debug/../lightDenseYOLO/mainwindow.cpp:69：对‘Detector::Detector(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)’未定义的引用
mainwindow.o：在函数‘Detector::detect_resized(image_t, int, int, float, bool)’中：
/home/lisaliu/code/build-TestDarkNet-Desktop_Qt_5_10_1_GCC_64bit-Debug/../lightDenseYOLO/yolo_v2_class.h:69：对‘Detector::detect(image_t, float, bool)’未定义的引用
mainwindow.o：在函数‘Detector::mat_to_image_resize(cv::Mat) const’中：
/home/lisaliu/code/build-TestDarkNet-Desktop_Qt_5_10_1_GCC_64bit-Debug/../lightDenseYOLO/yolo_v2_class.h:88：对‘Detector::get_net_height() const’未定义的引用
/home/lisaliu/code/build-TestDarkNet-Desktop_Qt_5_10_1_GCC_64bit-Debug/../lightDenseYOLO/yolo_v2_class.h:88：对‘Detector::get_net_width() const’未定义的引用
mainwindow.o：在函数‘Detector::mat_to_image(cv::Mat)::{lambda(image_t*)#1}::operator()(image_t*) const’中：
/home/lisaliu/code/build-TestDarkNet-Desktop_Qt_5_10_1_GCC_64bit-Debug/../lightDenseYOLO/yolo_v2_class.h:96：对‘Detector::free_image(image_t)’未定义的引用

**Comment by phongnhhn92** [comment]
`unix:!macx: LIBS += -L$$PWD/./ -ldarknet`
`INCLUDEPATH += $$PWD/. `
`DEPENDPATH** += $$PWD/. `

As you can see above, I called the darknet.so for those.
Also, I think you should add this in the .pro file since this project requires C+11

`CONFIG += c++11`
