### ISSUE TITLE
Code for generating training data with markers

### ISSUE THREAD

**Issue by cyberbeat** [phongnhhn92/lightDenseYOLO#3]
Could you share your code to generate the training data? What marker types did you try/train?

**Comment by phongnhhn92** [comment]
@cyberbeat 
Hello, in my [lightDenseYOLO](https://www.mdpi.com/1424-8220/18/6/1703/htm) paper, I have used my own designed marker from my [other](https://www.mdpi.com/1424-8220/17/9/1987/htm) paper (Figure 2). 

My marker design is simple for the task of drone landing and we can use it as the alternatives for other AR markers such as AruCo marker. The patter of the marker is quite easy to recreate and you can do it with any design software (in my case, I used AutoCAD). 

If you want to use my drone landing dataset then you can send a request email to my supervisor at parkgr@dongguk.edu. For more information about how I create my dataset, you can read my paper on marker detection (not using CNN) which I have mentioned above.

Feel free to ask me if you have more questions!
